# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginprojectfinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from topicpage import Ui_MainWindow50 


class Ui_MainWindow(object):
    def ok(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow50()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 568)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("border-bottom-right-radius:150px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 50, 575, 650))
        self.widget.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-bottom-right-radius:5px;\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        #
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(310, 290, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 128, 22, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"color:rgba(255,255,255,210);\n"
"border-radius: 6px;}\n"
"QPushButton:hover{\n"
"    background-color:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 128, 22, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"padding-left: 6px;\n"
"padding-top: 6px;\n"
"background-color:rgba(150,123,111,255);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        #
        self.pushButton.clicked.connect(self.ok)
        self.pushButton.clicked.connect(MainWindow.close)
        
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(360, 390, 30, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"   background:rgb(255, 67, 80);\n"
"   border: 2px solid rgb(125, 15, 31);\n"
"    border-radius: 7px;}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(420, 390, 30, 30))
        self.pushButton_6.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"   background:rgb(32, 53, 176);\n"
"   borer:5px solid rgb(37, 32, 76);\n"
"    border-radius: 7px;}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(310, 0, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 390, 30, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"   background:rgb(85, 85, 255);\n"
"   border: 2px solid rgb(0,50,200);\n"
"    border-radius: 7px;}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 150, 201, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom: 7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(310, 340, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 390, 30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"   background:rgb(182, 69, 59);\n"
"   border: 2px solid rgb(83, 18, 2);\n"
"    border-radius: 7px;}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(310, 80, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 210, 201, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom: 7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 340, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 128, 22, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"color:rgba(255,255,255,210);\n"
"border-radius: 6px;}\n"
"QPushButton:hover{\n"
"    background-color:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 128, 22, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"padding-left: 6px;\n"
"padding-top: 6px;\n"
"background-color:rgba(150,123,111,255);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(720, 450, 30, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"   background:rgb(255, 67, 80);\n"
"   border: 2px solid rgb(125, 15, 31);\n"
"    border-radius: 7px;}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setGeometry(QtCore.QRect(780, 450, 30, 30))
        self.pushButton_9.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"   background:rgb(32, 53, 176);\n"
"   borer:5px solid rgb(37, 32, 76);\n"
"    border-radius: 7px;}\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(640, 110, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(630, 100, 261, 430))
        self.label_6.setMinimumSize(QtCore.QSize(261, 430))
        self.label_6.setMaximumSize(QtCore.QSize(261, 420))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setUnderline(False)
        self.label_6.setFont(font)
        self.label_6.setAcceptDrops(True)
        self.label_6.setAccessibleName("")
        self.label_6.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius: 50px;")
        self.label_6.setLineWidth(0)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setGeometry(QtCore.QRect(670, 450, 30, 30))
        self.pushButton_10.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"   background:rgb(85, 85, 255);\n"
"   border: 2px solid rgb(0,50,200);\n"
"    border-radius: 7px;}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(670, 220, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom: 7px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(680, 390, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(830, 450, 30, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"   background:rgb(182, 69, 59);\n"
"   border: 2px solid rgb(83, 18, 2);\n"
"    border-radius: 7px;}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(680, 170, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(670, 260, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom: 7px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 0, 261, 421))
        self.label.setStyleSheet("border-image:url(:/newPrefix/login.jfif);\n"
"border-top-left-radius: 10px;\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Log In"))
        self.pushButton_7.setText(_translate("MainWindow", "G+"))
        self.pushButton_6.setText(_translate("MainWindow", "f"))
        self.label_4.setText(_translate("MainWindow", "WELCOME TO QUIZ"))
        self.pushButton_5.setText(_translate("MainWindow", "in"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "forgot your Name or RollNo. ?"))
        self.pushButton_3.setText(_translate("MainWindow", "Q"))
        self.label_2.setText(_translate("MainWindow", "Log In"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Roll No."))
        self.pushButton_2.setText(_translate("MainWindow", "Log In"))
        self.pushButton_8.setText(_translate("MainWindow", "G+"))
        self.pushButton_9.setText(_translate("MainWindow", "f"))
        self.label_5.setText(_translate("MainWindow", "WELCOME TO PYTHON QUIZ"))
        self.pushButton_10.setText(_translate("MainWindow", "in"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Name"))
        self.label_7.setText(_translate("MainWindow", "forgot your Name or RollNo. ?"))
        self.pushButton_4.setText(_translate("MainWindow", "Q"))
        self.label_8.setText(_translate("MainWindow", "Log In"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Roll No."))
import login


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
