# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 't3_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from t3_2 import Ui_MainWindow11


class Ui_MainWindow10(object):
    def ok(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow11()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()
        
    def setupUi(self, MainWindow10):
        MainWindow10.setObjectName("MainWindow10")
        MainWindow10.resize(480, 430)
        self.centralwidget = QtWidgets.QWidget(MainWindow10)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 480, 430))
        self.widget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(138, 243, 188, 255), stop:1 rgba(255, 255, 255, 255))")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 421, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setGeometry(QtCore.QRect(50, 80, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 160, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 240, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.NEXT = QtWidgets.QPushButton(self.widget,clicked =lambda:self.select())
        self.NEXT.setGeometry(QtCore.QRect(50, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NEXT.setFont(font)
        self.NEXT.setObjectName("NEXT")
        #
        self.NEXT.clicked.connect(self.ok)
        self.NEXT.clicked.connect(MainWindow10.close)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(240, 310, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(240, 340, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow10.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow10)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        MainWindow10.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow10)
        self.statusbar.setObjectName("statusbar")
        MainWindow10.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow10)
        QtCore.QMetaObject.connectSlotsByName(MainWindow10)

    def retranslateUi(self, MainWindow10):
        _translate = QtCore.QCoreApplication.translate
        MainWindow10.setWindowTitle(_translate("MainWindow10", "MainWindow"))
        self.label.setText(_translate("MainWindow10", "1"))
        self.label_2.setText(_translate("MainWindow10", "Which one of the following is a valid Python if statement ?"))
        self.radioButton.setText(_translate("MainWindow10", "if (a >= 2)"))
        self.radioButton_2.setText(_translate("MainWindow10", " if a>=2"))
        self.radioButton_3.setText(_translate("MainWindow10", " if (a => 2):"))
        self.NEXT.setText(_translate("MainWindow10", "NEXT"))
        self.label_3.setText(_translate("MainWindow10", "Your score is:"))
        self.label_4.setText(_translate("MainWindow10", "TextLabel"))

    #
    def select(self):
         r=0
         if self.radioButton_3.isChecked():
              r=r+20
              print("Out of 100 Your Score is")
              print(r)
              self.label_4.setNum(r)
         else:
              print(r)
              self.label_4.setNum(r)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow10 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow10()
    ui.setupUi(MainWindow10)
    MainWindow10.show()
    sys.exit(app.exec_())
