# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'topicpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from t1_1 import Ui_MainWindow0
from t2_1 import Ui_MainWindow5
from t3_1 import Ui_MainWindow10
from t4_1 import Ui_MainWindow15
from t5_1 import Ui_MainWindow20
from t6_1 import Ui_MainWindow25


class Ui_MainWindow50(object):
    def ok1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow0()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()

    def ok2(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow5()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()

    def ok3(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow10()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()

    def ok4(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow15()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()

    def ok5(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow20()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()

    def ok6(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow25()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()
        
    def setupUi(self, MainWindow50):
        MainWindow50.setObjectName("MainWindow50")
        MainWindow50.resize(1186, 837)
        self.centralwidget = QtWidgets.QWidget(MainWindow50)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(120, 0, 911, 751))
        self.widget.setStyleSheet("background-image: url(:/image/snow.jpeg);\n"
"background-color:rgba(255,255,255,255);\n"
"border-top-left-radius:150 px;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 20, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(42, 135, 202, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.label.setObjectName("label")
        self.basicsbtm = QtWidgets.QPushButton(self.widget)
        self.basicsbtm.setGeometry(QtCore.QRect(260, 140, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.basicsbtm.setFont(font)
        self.basicsbtm.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(176, 11, 173, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.basicsbtm.setObjectName("basicsbtm")
        #
        self.basicsbtm.clicked.connect(self.ok1)
        self.basicsbtm.clicked.connect(MainWindow50.close)
        
        self.datatypesbtn = QtWidgets.QPushButton(self.widget)
        self.datatypesbtn.setGeometry(QtCore.QRect(260, 220, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.datatypesbtn.setFont(font)
        self.datatypesbtn.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(137, 54, 216, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.datatypesbtn.setObjectName("datatypesbtn")

        self.datatypesbtn.clicked.connect(self.ok2)
        self.datatypesbtn.clicked.connect(MainWindow50.close)
        
        self.controlstsbtn = QtWidgets.QPushButton(self.widget)
        self.controlstsbtn.setGeometry(QtCore.QRect(260, 310, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.controlstsbtn.setFont(font)
        self.controlstsbtn.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(68, 195, 142, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.controlstsbtn.setObjectName("controlstsbtn")

        #
        self.controlstsbtn.clicked.connect(self.ok3)
        self.controlstsbtn.clicked.connect(MainWindow50.close)
        
        self.oopsbtn = QtWidgets.QPushButton(self.widget)
        self.oopsbtn.setGeometry(QtCore.QRect(260, 410, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.oopsbtn.setFont(font)
        self.oopsbtn.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(37, 193, 179, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.oopsbtn.setObjectName("oopsbtn")
        #
        self.oopsbtn.clicked.connect(self.ok4)
        self.oopsbtn.clicked.connect(MainWindow50.close)
        
        self.numpybtn = QtWidgets.QPushButton(self.widget)
        self.numpybtn.setGeometry(QtCore.QRect(260, 600, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.numpybtn.setFont(font)
        self.numpybtn.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(121, 213, 76, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.numpybtn.setObjectName("numpybtn")

        #
        self.numpybtn.clicked.connect(self.ok6)
        self.numpybtn.clicked.connect(MainWindow50.close)
        
        self.filehandbtn = QtWidgets.QPushButton(self.widget)
        self.filehandbtn.setGeometry(QtCore.QRect(260, 510, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.filehandbtn.setFont(font)
        self.filehandbtn.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(164, 2, 90, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.filehandbtn.setObjectName("filehandbtn")

        #
        self.filehandbtn.clicked.connect(self.ok5)
        self.filehandbtn.clicked.connect(MainWindow50.close)
        
        MainWindow50.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow50)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1186, 26))
        self.menubar.setObjectName("menubar")
        MainWindow50.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow50)
        self.statusbar.setObjectName("statusbar")
        MainWindow50.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow50)
        QtCore.QMetaObject.connectSlotsByName(MainWindow50)

    def retranslateUi(self, MainWindow50):
        _translate = QtCore.QCoreApplication.translate
        MainWindow50.setWindowTitle(_translate("MainWindow50", "MainWindow"))
        self.label.setText(_translate("MainWindow50", "    Select One Topic"))
        self.basicsbtm.setText(_translate("MainWindow50", "Baics of Python"))
        self.datatypesbtn.setText(_translate("MainWindow50", "Data Types"))
        self.controlstsbtn.setText(_translate("MainWindow50", "Control Statements"))
        self.oopsbtn.setText(_translate("MainWindow50", "OOPS in Python"))
        self.numpybtn.setText(_translate("MainWindow50", "Numpy & Pandas Libraries"))
        self.filehandbtn.setText(_translate("MainWindow50", "File Handling"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow50 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow50()
    ui.setupUi(MainWindow50)
    MainWindow50.show()
    sys.exit(app.exec_())
